### ISSUE TITLE
Exception: There was an issue getting the current card because review is not currently active.

### ISSUE THREAD

**Issue by GrimPixel** [RuzuStudios/ruzu-pop-ups#11]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.55 (01caec2a) Python 3.10.9 Qt 6.4.1 PyQt 6.4.0
Platform: Linux-6.1.1-arch1-1-x86_64-with-glibc2.36
Flags: frz=False ao=True sv=2
Add-ons, last update check: 2023-01-02 17:59:05
Add-ons possibly involved: ⁨Ruzu Pop-ups⁩

Caught exception:
Traceback (most recent call last):
  File "/home/user/.local/share/Anki2/addons21/1736169259/gui/options.py", line 114, in show_next_card_and_close
    self.ruzu_schedule.exec_schedule()
  File "/home/user/.local/share/Anki2/addons21/1736169259/ruzu_schedule.py", line 24, in exec_schedule
    self.alarm_func()
  File "/home/user/.local/share/Anki2/addons21/1736169259/__init__.py", line 25, in show_next_card
    ruzu_popup.show_popup()
  File "/home/user/.local/share/Anki2/addons21/1736169259/gui/popup.py", line 203, in show_popup
    self.show_question_popup()
  File "/home/user/.local/share/Anki2/addons21/1736169259/gui/popup.py", line 213, in show_question_popup
    current_card = self.anki_utils.get_current_card()
  File "/home/user/.local/share/Anki2/addons21/1736169259/anki_utils.py", line 105, in get_current_card
    raise Exception('There was an issue getting the current card because review is not currently active.')
Exception: There was an issue getting the current card because review is not currently active.

**Comment by CharlesHenry** [comment]
I think this is a duplicate of #2. Is this happening when there are no cards left to review?

**Comment by GrimPixel** [comment]
No. It happened to any deck.

**Comment by CharlesHenry** [comment]
I'm unable to reproduce this error. I think the plugin is not compatible with Linux. I've not tested this myself Linux so will have to look into it when I can.

**Comment by GrimPixel** [comment]
This is what I found out:
To avoid this error, I have to open a review window. Then I got a new error:
`Exception: There was an issue getting the current card because review is not currently active.`
It led to the “Default” deck, which was empty. This is the reason: that dropdown list always has a “Default”, no matter if it is empty.

**Comment by GrimPixel** [comment]
That is it.
