### ISSUE TITLE
I can't grade a card

### ISSUE THREAD

**Issue by pablo-s-dev** [RuzuStudios/ruzu-pop-ups#15]
Debug info:
Anki 2.1.60 (76d88073) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Windows-10-10.0.19044
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-05-01 11:16:29

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Pablo\AppData\Roaming\Anki2\addons21\1736169259\gui\popup.py", line 52, in <lambda>
    self.btn[2].clicked.connect(lambda _: self.send_answer("Good"))
  File "C:\Users\Pablo\AppData\Roaming\Anki2\addons21\1736169259\gui\popup.py", line 261, in send_answer
    answer_result = self.anki_utils.answer_card(ease)
  File "C:\Users\Pablo\AppData\Roaming\Anki2\addons21\1736169259\anki_utils.py", line 68, in answer_card
  File "aqt.reviewer", line 457, in _answerCard
  File "aqt.reviewer", line 463, in _after_answering
  File "aqt.reviewer", line 812, in check_timebox
  File "anki.collection", line 1247, in timeboxReached
  File "anki._legacy", line 80, in __getattr__
AttributeError: 'Collection' object has no attribute '_startTime'

**Comment by pablo-s-dev** [comment]
It seems like it's working after I activated the "show answer timer" in deck options

**Comment by CharlesHenry** [comment]
That's interesting, I will have a look
