### ISSUE TITLE
An error after each my answer

### ISSUE THREAD

**Issue by Anatoly042018** [RuzuStudios/ruzu-pop-ups#17]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.63 (f356f177) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
Platform: Windows-10-10.0.22000
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-09-19 07:55:48

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.taskman", line 90, in wrapped_done
  File "aqt.operations", line 125, in wrapped_done
  File "aqt.reviewer", line 459, in after_answer
  File "aqt.reviewer", line 473, in _after_answering
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by huachuman** [comment]
SAME EXACT ERROR!!!

Did you ever figure it out?
