### ISSUE TITLE
AttributeError: 'DeckManager' object has no attribute 'all_names_and_ids'

### ISSUE THREAD

**Issue by CoffeeDrinkRabbit** [RuzuStudios/ruzu-pop-ups#3]
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.7
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-02-25 02:58:28
相关扩展:⁨Ruzu Pop-ups⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/xiamu/Library/Application Support/Anki2/addons21/1736169259/__init__.py", line 48, in <lambda>
    options_action.triggered.connect(lambda _: show_options())
  File "/Users/xiamu/Library/Application Support/Anki2/addons21/1736169259/__init__.py", line 34, in show_options
    ruzu_options = RuzuOptions(mw, ruzu_schedule)
  File "/Users/xiamu/Library/Application Support/Anki2/addons21/1736169259/gui/options.py", line 26, in __init__
    decks = self.anki_utils.get_decks()
  File "/Users/xiamu/Library/Application Support/Anki2/addons21/1736169259/anki_utils.py", line 32, in get_decks
    return decks.all_names_and_ids()
AttributeError: 'DeckManager' object has no attribute 'all_names_and_ids'

**Comment by CharlesHenry** [comment]
Hello @CoffeeDrinkRabbit, thanks for raising this. The `all_names_and_ids` function was added in Anki v2.1.28 and you're using v2.1.26 so you should be able to resolve this with a simple Anki update. I'll set the minimum required version for this plugin to 2.1.28 in the manifest to prevent others having this problem. I'd like to keep this issue open until I've sorted that.
