### ISSUE TITLE
annoying bug

### ISSUE THREAD

**Issue by DR-3araby** [RuzuStudios/ruzu-pop-ups#7]
actually, I'm very happy about this add-on 
but I'm facing a bug that causes the app to crash after each card pops up
after answering it shows this error

`Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.53 (96bacf79) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-06-10 01:06:04

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.taskman", line 90, in wrapped_done
  File "aqt.operations", line 125, in wrapped_done
  File "aqt.reviewer", line 433, in after_answer
AttributeError: 'NoneType' object has no attribute 'load'
`
![image](https://user-images.githubusercontent.com/63804491/172966168-e65bc588-3844-4a1d-9c08-71259e3b9fa6.png)

**Comment by CharlesHenry** [comment]
@DR-3araby are you still getting this issue with the latest version of Anki and the addon?

**Comment by Hosseingsd** [comment]
today i used the addon and this happened to me too

**Comment by khonkhortisan** [comment]
[workaround] An autohotkey script that closes the error window every time it shows
AnkiRuzuError.ahk
```ahk
while True {
	WinWaitActive, ahk_class Qt642QWindowIcon
	WinGetPos, X, Y, Width, Height
	if(Width=516 and Height=439)
		WinClose, ahk_class Qt642QWindowIcon
}
```

**Comment by Hosseingsd** [comment]
> [⤼ workaround][🪟 windows] An autohotkey script that closes the error window every time it shows AnkiRuzuError.ahk
> 
> ```ahk
> while True {
> 	WinWaitActive, ahk_class Qt642QWindowIcon
> 	WinGetPos, X, Y, Width, Height
> 	if(Width=516 and Height=439)
> 		WinClose, ahk_class Qt642QWindowIcon
> }
> ```
> 
> ✔️ doesn't error with
> 
> ```
>     
>     Anki 2.1.56 (07fd88dd) Python 3.9.15 Qt 6.4.0 PyQt 6.4.0
>     Platform: Windows-10-10.0.19045
>     Flags: frz=True ao=True sv=3
>     Add-ons, last update check: 2023-05-19 20:30:27
>     
>     
>     ===Add-ons (active)===
>     (add-on provided name [Add-on folder, installed at, version, is config changed])
>     Add a tag to notes with missing media ['2027876532', 2022-06-04T17:28, 'None', '']
>     Anki Preview Reloader ['571150035', 2023-04-22T12:29, '1.0.0', '']
>     AnkiConnect ['2055492159', 2023-04-11T10:20, 'None', '']
>     Auto Ease Factor ['1672712021', 2021-03-21T11:11, 'None', mod]
>     AwesomeTTS - Add speech to your flashcards ['1436550454', 2023-04-09T19:00, 'None', '']
>     Batch Editing ['291119185', 2019-06-04T16:10, 'None', '']
>     Cloze Hide All ['1709973686', 2021-09-11T03:00, '21.9.11i107', mod]
>     Cloze Overlapper for Anki 21 ['109531687', 2021-01-11T19:12, 'None', '']
>     Delay siblings ['1369579727', 2022-06-03T16:05, 'None', '']
>     FSRS4Anki Helper ['759844606', 2023-05-16T18:44, 'None', '']
>     Fix invalid card IDs ['196231552', 2021-11-25T17:33, 'None', '']
>     Leaderboard ['41708974', 2023-01-15T02:53, 'None', mod]
>     Learn now  Grade now ['1021636467', 2023-05-08T02:53, 'None', '']
>     MorphMan for Anki 21 ['900801631', 2023-01-10T12:01, 'None', '']
>     Review Heatmap ['1771074083', 2022-06-29T18:43, 'None', '']
>     Ruzu Pop-ups ['1736169259', 2022-12-26T17:07, 'v0.0.4', mod]
>     extended editor for field for tables searchreplace ['805891399', 2022-03-13T03:51, 'None', '']
>     
>     ===IDs of active AnkiWeb add-ons===
>     1021636467 109531687 1369579727 1436550454 1672712021 1709973686 1736169259 1771074083 196231552 2027876532 2055492159 291119185 41708974 571150035 759844606 805891399 900801631
> ```
> 
> ❌ does error with
> 
> ```
>     
>     Anki 2.1.58 (ab8b1465) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
>     Platform: Windows-10-10.0.19045
>     Flags: frz=True ao=True sv=3
>     Add-ons, last update check: 2023-05-19 17:41:46
>     
>     
>     ===Add-ons (active)===
>     (add-on provided name [Add-on folder, installed at, version, is config changed])
>     '' ['DecksAddBrowseStatsSync', 0, 'None', '']
>     '' ['cloze_overlapper', 0, 'None', '']
>     '' ['enableplover', 0, 'None', '']
>     '' ['tagtovlc', 0, 'None', mod]
>     3 add-ons merged quicker anki explain deletion explain database check ['777545149', 2019-09-26T06:03, 'None', '']
>     Add Card Do First Review ['1394953283', 2020-11-11T06:40, 'None', '']
>     Add Parent Tag To Every Tag In A Deck ['543106186', 2019-11-20T18:30, 'None', '']
>     Advanced Copy Fields ['1898445115', 2019-05-03T11:46, 'None', '']
>     Almost Mandatory Tags ['1386232247', 2022-12-28T09:51, 'None', '']
>     Anki JavaScript API ['1490471827', 2021-02-19T12:54, 'None', '']
>     Anki Preview Reloader ['571150035', 2023-04-22T12:29, '1.0.0', '']
>     Anki X Markdown X MindMap ['728482867', 2022-07-08T21:07, 'None', '']
>     AnkiConnect ['2055492159', 2023-04-11T10:20, 'None', mod]
>     AnkiWebView Inspector ['31746032', 2022-04-08T12:44, 'None', '']
>     Answer Visual Confirmation ['1208806023', 2008-04-21T12:27, 'None', '']
>     Auto Ease Factor ['1672712021', 2021-03-21T11:11, 'None', mod]
>     Batch Editing ['291119185', 2019-06-04T16:10, 'None', '']
>     CC-CEDICT for Anki Chinese dictionary ['418828045', 2022-03-23T05:22, 'None', mod]
>     CN Bulk Generate Chinese Hanzi Homophone List to field ['1709020234', 2017-09-18T00:41, 'None', '']
>     Chinese Companion - frequency sort HSK suspend heisig support and more ['2129668097', 2019-05-20T01:02, 'None', '']
>     Chinese Pinyin Translator Zhuyin Bopomofo Gwoyeu Romatzyh ['1792056402', 2018-11-08T19:27, 'None', mod]
>     Chinese Prestudy ['882364911', 2020-11-02T22:43, 'None', '']
>     Chinese Stats ['1959794557', 2022-01-29T23:06, 'None', mod]
>     Chinese Support Redux v0142 ['1128979221', 2021-03-28T19:19, 'None', mod]
>     Chinese Vocabulary Generator ['1370756741', 2021-02-24T00:07, 'None', '']
>     Chinese Words Finder ['2048169015', 2020-07-07T05:32, 'None', '']
>     Chinese-Text-Scanner ['2121493325', 2020-06-27T21:53, 'None', mod]
>     Cloze Anything ['330680661', 2021-12-08T23:34, 'None', '']
>     Cloze Overlapper for Anki 21 ['109531687', 2021-01-11T19:12, 'None', '']
>     Color Confirmation ['1084228676', 2020-03-14T05:13, 'None', mod]
>     Content Injector ['166455199', 2020-09-03T09:08, 'None', mod]
>     Convert Subdecks to Tag Hierarchy ['1172858842', 2023-02-07T10:15, 'None', '']
>     Create subs2srs cards with mpv  interactive subs ['832294226', 2023-03-08T03:45, 'None', '']
>     CrowdAnki JSON exportimport Edit history Collaborate on deck creation ['1788670778', 2023-02-03T16:58, 'None', '']
>     Deck Browser CSS ['153779542', 2022-10-18T08:53, 'None', '']
>     DeepL Translator ['972129549', 2022-07-30T15:16, '1.0.0', mod]
>     Delay siblings ['1369579727', 2022-06-03T16:05, 'None', mod]
>     DrawingPad ['370778248', 2019-08-21T21:36, 'None', '']
>     Editor Live Preview ['1960039667', 2023-03-24T09:35, 'None', mod]
>     FSRS4Anki Helper ['759844606', 2023-05-16T18:44, 'None', mod]
>     Fill the blanks - Multiple typecloze support ['1933645497', 2023-05-03T11:21, 'None', '']
>     Find and Replace in Card templatesNotetypesHTML ['992153575', 2021-09-16T23:34, 'None', '']
>     Flexible Cloze ['1632356464', 2023-01-21T08:04, 'None', '']
>     HTML Window source ['1214415810', 2020-02-18T05:20, 'None', '']
>     HyperTTS - Add speech to your flashcards ['111623432', 2023-02-24T20:35, 'None', mod]
>     Image Occlusion Enhanced ['1374772155', 2022-04-09T00:15, 'None', '']
>     Incremental Reading v4116 unofficial clone ['999215520', 2023-03-18T22:18, 'None', '']
>     Learn now  Grade now ['1021636467', 2023-05-08T02:53, 'None', '']
>     Life Drain ['715575551', 2022-09-18T03:42, 'None', mod]
>     Markdown and KaTeX Support ['1087328706', 2023-05-06T04:28, 'None', '']
>     Migaku Chinese ['498302176', 2021-04-12T15:29, 'None', mod]
>     Migaku Retirement ['1666520655', 2021-01-13T16:37, 'None', mod]
>     Mindmap from tag hierarchy ['965278890', 2022-11-16T02:55, 'None', '']
>     MorphMan for Anki 21 ['900801631', 2023-01-10T12:01, 'None', '']
>     Motivanki ['663438166', 2022-06-23T08:38, 'None', '']
>     Neo Anki Leaderboard ['1894428367', 2023-03-09T12:27, 'None', mod]
>     No Distractions Full Screen Clean review interface WORKING ['1799768115', 2022-11-20T11:04, 'v4.1.8', mod]
>     Pop-up Wikipedia Beta ['395343016', 2020-01-08T19:58, 'None', '']
>     Progress Bar cards done cards left secondscard time spentleft and ETA ['1097423555', 2022-08-05T04:01, 'None', mod]
>     Puppy Reinforcement ['1722658993', 2020-03-02T12:23, 'None', '']
>     Quick note and deck buttons Fork for 21 ['1331140127', 2022-05-23T06:13, 'None', '']
>     Quizlet to Anki 21 Importer with audio support ['1362209126', 2023-05-18T22:30, 'None', '']
>     Review Heatmap ['1771074083', 2022-06-29T18:43, 'None', '']
>     Review Hotmouse ['1928346827', 2022-05-16T21:25, '2.6', mod]
>     Ruzu Pop-ups ['1736169259', 2022-12-26T17:07, 'v0.0.4', mod]
>     Search and Replace Tags ['138501288', 2018-02-08T16:03, 'None', '']
>     Update lookup Tags ['1715601279', 2018-11-19T10:25, 'None', '']
>     extended editor for field for tables searchreplace ['805891399', 2022-03-13T03:51, 'None', '']
>     right hand reviews  hjkl answer shortcuts  Handy Answer Keys configurable ['850294128', 2021-12-06T07:00, 'None', mod]
>     
>     ===IDs of active AnkiWeb add-ons===
>     1021636467 1084228676 1087328706 109531687 1097423555 111623432 1128979221 1172858842 1208806023 1214415810 1331140127 1362209126 1369579727 1370756741 1374772155 138501288 1386232247 1394953283 1490471827 153779542 1632356464 166455199 1666520655 1672712021 1709020234 1715601279 1722658993 1736169259 1771074083 1788670778 1792056402 1799768115 1894428367 1898445115 1928346827 1933645497 1959794557 1960039667 2048169015 2055492159 2121493325 2129668097 291119185 31746032 330680661 370778248 395343016 418828045 498302176 543106186 571150035 663438166 715575551 728482867 759844606 777545149 805891399 832294226 850294128 882364911 900801631 965278890 972129549 992153575 999215520
> ```

How did you export this texts?

**Comment by khonkhortisan** [comment]
> How did you export this texts?

Help→About→Copy Debug Info

---
❌❌ I disabled some of my addons, and the error changed from 'load' to 'id', which I'll take as evidence that there are at least two currently-incompatible addons.
```
Error 
Se ha producido un error. Por favor inicia la Anki manteniendo presionadas ples teclas Mayús y la flecha hacia abajo, lo que desactivará temporalmente los extensiones que tienes instaladas. 
Si este error persiste sólo cuando tienes las extensiones activadas, utiliza Herramientas > Menú de Extensiones para deshabilitar alguna extensión y reinicia el Anki, repitiendo este proceso hasta que descubras qué extensión en concreto es la que causa el problema 
Cuando hayas descubierto la extensión que causaba el problema, por favor informa de esto a [sitio de soporte de extensiones](https://forums.ankiweb.net/c/add-ons/11). 
Información de depuración:
Anki 2.1.58 (ab8b1465) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-05-19 17:41:46

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.taskman", line 90, in wrapped_done
  File "aqt.operations", line 125, in wrapped_done
  File "aqt.reviewer", line 447, in after_answer
  File "aqt.reviewer", line 461, in _after_answering
AttributeError: 'NoneType' object has no attribute 'id'
```
```
    
    Anki 2.1.58 (ab8b1465) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
    Platform: Windows-10-10.0.19045
    Flags: frz=True ao=True sv=3
    Add-ons, last update check: 2023-05-19 17:41:46
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['DecksAddBrowseStatsSync', 0, 'None', '']
    '' ['enableplover', 0, 'None', '']
    '' ['tagtovlc', 0, 'None', mod]
    3 add-ons merged quicker anki explain deletion explain database check ['777545149', 2019-09-26T06:03, 'None', '']
    Add Card Do First Review ['1394953283', 2020-11-11T06:40, 'None', '']
    Almost Mandatory Tags ['1386232247', 2022-12-28T09:51, 'None', '']
    Anki JavaScript API ['1490471827', 2021-02-19T12:54, 'None', '']
    Anki Preview Reloader ['571150035', 2023-04-22T12:29, '1.0.0', '']
    Anki X Markdown X MindMap ['728482867', 2022-07-08T21:07, 'None', '']
    AnkiConnect ['2055492159', 2023-04-11T10:20, 'None', mod]
    AnkiWebView Inspector ['31746032', 2022-04-08T12:44, 'None', '']
    Answer Visual Confirmation ['1208806023', 2008-04-21T12:27, 'None', '']
    Auto Ease Factor ['1672712021', 2021-03-21T11:11, 'None', mod]
    Batch Editing ['291119185', 2019-06-04T16:10, 'None', '']
    CC-CEDICT for Anki Chinese dictionary ['418828045', 2022-03-23T05:22, 'None', mod]
    CN Bulk Generate Chinese Hanzi Homophone List to field ['1709020234', 2017-09-18T00:41, 'None', '']
    Chinese Companion - frequency sort HSK suspend heisig support and more ['2129668097', 2019-05-20T01:02, 'None', '']
    Chinese Pinyin Translator Zhuyin Bopomofo Gwoyeu Romatzyh ['1792056402', 2018-11-08T19:27, 'None', mod]
    Chinese Prestudy ['882364911', 2020-11-02T22:43, 'None', '']
    Chinese Stats ['1959794557', 2022-01-29T23:06, 'None', mod]
    Chinese Support Redux v0142 ['1128979221', 2021-03-28T19:19, 'None', mod]
    Chinese Vocabulary Generator ['1370756741', 2021-02-24T00:07, 'None', '']
    Chinese Words Finder ['2048169015', 2020-07-07T05:32, 'None', '']
    Chinese-Text-Scanner ['2121493325', 2020-06-27T21:53, 'None', mod]
    Cloze Overlapper for Anki 21 ['109531687', 2021-01-11T19:12, 'None', '']
    Content Injector ['166455199', 2020-09-03T09:08, 'None', mod]
    Deck Browser CSS ['153779542', 2022-10-18T08:53, 'None', '']
    DrawingPad ['370778248', 2019-08-21T21:36, 'None', '']
    Editor Live Preview ['1960039667', 2023-03-24T09:35, 'None', mod]
    FSRS4Anki Helper ['759844606', 2023-05-16T18:44, 'None', mod]
    Fill the blanks - Multiple typecloze support ['1933645497', 2023-05-03T11:21, 'None', '']
    Find and Replace in Card templatesNotetypesHTML ['992153575', 2021-09-16T23:34, 'None', '']
    HyperTTS - Add speech to your flashcards ['111623432', 2023-02-24T20:35, 'None', mod]
    Image Occlusion Enhanced ['1374772155', 2022-04-09T00:15, 'None', '']
    Incremental Reading v4116 unofficial clone ['999215520', 2023-03-18T22:18, 'None', '']
    Learn now  Grade now ['1021636467', 2023-05-08T02:53, 'None', '']
    Migaku Chinese ['498302176', 2021-04-12T15:29, 'None', mod]
    Migaku Retirement ['1666520655', 2021-01-13T16:37, 'None', mod]
    Mindmap from tag hierarchy ['965278890', 2022-11-16T02:55, 'None', '']
    MorphMan for Anki 21 ['900801631', 2023-01-10T12:01, 'None', '']
    Quick note and deck buttons Fork for 21 ['1331140127', 2022-05-23T06:13, 'None', '']
    Readable Addons Folder ['5720472', 2023-04-15T19:51, 'None', '']
    Review Heatmap ['1771074083', 2022-06-29T18:43, 'None', '']
    Review Hotmouse ['1928346827', 2022-05-16T21:25, '2.6', mod]
    Ruzu Pop-ups ['1736169259', 2022-12-26T17:07, 'v0.0.4', mod]
    Search and Replace Tags ['138501288', 2018-02-08T16:03, 'None', '']
    Update lookup Tags ['1715601279', 2018-11-19T10:25, 'None', '']
    extended editor for field for tables searchreplace ['805891399', 2022-03-13T03:51, 'None', '']
    right hand reviews  hjkl answer shortcuts  Handy Answer Keys configurable ['850294128', 2021-12-06T07:00, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    1021636467 109531687 111623432 1128979221 1208806023 1331140127 1370756741 1374772155 138501288 1386232247 1394953283 1490471827 153779542 166455199 1666520655 1672712021 1709020234 1715601279 1736169259 1771074083 1792056402 1928346827 1933645497 1959794557 1960039667 2048169015 2055492159 2121493325 2129668097 291119185 31746032 370778248 418828045 498302176 571150035 5720472 728482867 759844606 777545149 805891399 850294128 882364911 900801631 965278890 992153575 999215520
```

**Comment by khonkhortisan** [comment]
…it throws the id error with only ruzu enabled??!

**Comment by huachuman** [comment]
I am getting the same error did anyone succeed in solving this? 

Anki 2.1.66 (70506aeb) Python 3.9.15 Qt 6.5.2 PyQt 6.5.2
Platform: Windows-10-10.0.25231
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-10-10 14:47:24

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.taskman", line 90, in wrapped_done
  File "aqt.operations", line 127, in wrapped_done
  File "aqt.reviewer", line 465, in after_answer
  File "aqt.reviewer", line 479, in _after_answering
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by kafujo** [comment]
I was using it on some old version of Anki (like 2.0) and it was working just fine, with no error. I finally decided to upgrade to the newest version of Anki, which made me convert my decks to the v3 scheduling. After this, Ruzu Popups no longer worked. I tried downgrading my Anki, and Ruzu started working again except I kept getting the same error you guys are getting. No matter how far I downgraded it, I would get the error. So I think it is something with the change to v3.
