### ISSUE TITLE
AttributeError: 'AnkiApp' object has no attribute 'desktop'

### ISSUE THREAD

**Issue by GrimPixel** [RuzuStudios/ruzu-pop-ups#8]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (88e539aa) Python 3.10.5 Qt 6.3.1 PyQt 6.3.1
Platform: Linux
Flags: frz=False ao=True sv=2
Add-ons, last update check: 2022-07-29 06:38:23
Add-ons possibly involved: ⁨Ruzu Pop-ups⁩

Caught exception:
Traceback (most recent call last):
  File "/home/grim/.local/share/Anki2/addons21/1736169259/ruzu_schedule.py", line 24, in exec_schedule
    self.alarm_func()
  File "/home/grim/.local/share/Anki2/addons21/1736169259/__init__.py", line 24, in show_next_card
    ruzu_popup.show_popup()
  File "/home/grim/.local/share/Anki2/addons21/1736169259/gui/popup.py", line 202, in show_popup
    self.show_question_popup()
  File "/home/grim/.local/share/Anki2/addons21/1736169259/gui/popup.py", line 219, in show_question_popup
    self.set_card_position()
  File "/home/grim/.local/share/Anki2/addons21/1736169259/gui/popup.py", line 84, in set_card_position
    screen_geometry = self.parent.app.desktop().availableGeometry()
AttributeError: 'AnkiApp' object has no attribute 'desktop'

**Comment by CharlesHenry** [comment]
This bug was resolved in v0.0.3
